# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - name: archive build files
      uses: actions/upload-artifact@v2
      with:
        name: buildFolder
        path: build
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with: 
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         known_hosts: 'placeholder' 
      - name: Add known hosts 
        run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: download build folder
        uses: actions/download-artifact@v2
        with: 
          name: buildFolder
          path: build
      - name: Deploy using rsync
        run: rsync -avz -e 'ssh -p ${{ secrets.SSH_PORT }}' buildFolder ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/kanban
